name = "snapprice"
compatibility_date = "2025-04-01"
pages_build_output_dir = "."
account_id = "eb5577c835cc05e93bf3b1650db73a9e"

[[kv_namespaces]]
binding = "USERS"
id = "89de6c5d433b426dae7fbe4fe148b2f1"
